#### 1. Write Python Programs to use various operators in Python



In [1]:
def various_operators(list_1, list_2, function):
    list_3 = []
    if len(list_1) != len(list_2):
        print("Please provide both lists with equal length")
    elif function == 'add':
        for i in range(len(list_1)):
            list_3.append(list_1[i] + list_2[i])
        return list_3
    elif function == 'subtract':
        for i in range(len(list_1)):
            list_3.append(list_1[i] - list_2[i])
        return list_3
    elif function == 'multiply':
        for i in range(len(list_1)):
            list_3.append(list_1[i] * list_2[i])
        return list_3
    elif function == 'divide':
        for i in range(len(list_1)):
            list_3.append(round(list_1[i] / list_2[i],2))
        return list_3
    elif function == 'modulo':
        for i in range(len(list_1)):
            list_3.append(round(list_1[i] % list_2[i],2))
        return list_3
    elif function == 'square':
        list_4 = []
        for i in range(len(list_1)):
            list_3.append(round((list_1[i])**2,2))
            list_4.append(round((list_2[i])**2,2))
        return list_3 + list_4
    elif function == 'cube':
        list_4 = []
        for i in range(len(list_1)):
            list_3.append(round((list_1[i])**3,2))
            list_4.append(round((list_2[i])**3,2))
        return list_3 + list_4
    else:
        print('Please provide a valid arithmetic operator like "add",\
               "subtract", "multiply", divide", "module", "square" and "cube"')

#### 2. Create list of elements and slice and dice it



In [5]:
# Initialize list
Lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
 
# Display list
print(Lst[::2])

# Display list
print(Lst[1::2])

# Display list
print(Lst[:5])

# Display list
print(Lst[-5:])

# Display list
print(Lst[6:])

[1, 3, 5, 7, 9, 11]
[2, 4, 6, 8, 10]
[1, 2, 3, 4, 5]
[7, 8, 9, 10, 11]
[7, 8, 9, 10, 11]


#### 3. Using while loop accept numbers until sum of numbers is less than 100



In [6]:
mySum = 0
num = 0
while mySum < 100:
    num += 1
    theSum = num
    mySum = theSum + num

print(num, theSum, mySum)

50 50 100


#### 4. Write a python program Read & write Excel files 



In [8]:
from openpyxl import Workbook
import time

book = Workbook()
sheet = book.active

sheet['A1'] = 'Name'
sheet['A2'] = 'Dalvi Moin'

now = time.strftime("%x")
sheet['A3'] = now

book.save("sample.xlsx")

#### 6. Create a 3x3 matrix with values ranging from 2 to 10 using numpy



In [9]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


#### 7. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array



In [10]:
import numpy as np
print("Original List               : ",[12.23, 13.32, 100, 36.32])
a = np.array([12.23, 13.32, 100, 36.32])
print("One-dimensional NumPy array : ",a)

Original List               :  [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array :  [ 12.23  13.32 100.    36.32]


#### 8. "Write a Python program to create a null vector of size 10 and update sixth value to 11.



In [11]:
import numpy as np
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
